name: riverpod_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Riverpod
  flutter_riverpod: ^2.1.3
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.18.5+1

  # Freezed
  freezed_annotation: ^2.2.0

  # Retrofit
  retrofit: ^3.3.1

  # Dio
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Freezed
  freezed: ^2.3.2

  # Retrofit
  retrofit_generator: ^4.2.0
  json_serializable: ^6.6.0

  # Build Runner
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
