// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/user_data_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 5788514939070495532),
      name: 'UserDataModel',
      lastPropertyId: const IdUid(15, 8418095341156710762),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8142160169920548244),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(3, 1580052332813176949),
            name: 'activity',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 2709354203586908039),
            name: 'type',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 4925416794264091475),
            name: 'participants',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 3779738329430608850),
            name: 'price',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 6664435693509081332),
            name: 'link',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 9217832627989040780),
            name: 'key',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(15, 8418095341156710762),
            name: 'accessibility',
            type: 8,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 5788514939070495532),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        6676600451827140482,
        8125858274688974175,
        4986972280128883939,
        3051769538903389671,
        7924711319947453250,
        2179329984912906335,
        7704156817749290466
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    UserDataModel: EntityDefinition<UserDataModel>(
        model: _entities[0],
        toOneRelations: (UserDataModel object) => [],
        toManyRelations: (UserDataModel object) => {},
        getId: (UserDataModel object) => object.id,
        setId: (UserDataModel object, int id) {
          object.id = id;
        },
        objectToFB: (UserDataModel object, fb.Builder fbb) {
          final activityOffset = fbb.writeString(object.activity);
          final typeOffset = fbb.writeString(object.type);
          final linkOffset = fbb.writeString(object.link);
          final keyOffset = fbb.writeString(object.key);
          fbb.startTable(16);
          fbb.addInt64(0, object.id);
          fbb.addOffset(2, activityOffset);
          fbb.addOffset(9, typeOffset);
          fbb.addInt64(10, object.participants);
          fbb.addFloat64(11, object.price);
          fbb.addOffset(12, linkOffset);
          fbb.addOffset(13, keyOffset);
          fbb.addFloat64(14, object.accessibility);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = UserDataModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..activity = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..type = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 22, '')
            ..participants =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0)
            ..price =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 26, 0)
            ..link = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 28, '')
            ..key = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 30, '')
            ..accessibility =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 32, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [UserDataModel] entity fields to define ObjectBox queries.
class UserDataModel_ {
  /// see [UserDataModel.id]
  static final id =
      QueryIntegerProperty<UserDataModel>(_entities[0].properties[0]);

  /// see [UserDataModel.activity]
  static final activity =
      QueryStringProperty<UserDataModel>(_entities[0].properties[1]);

  /// see [UserDataModel.type]
  static final type =
      QueryStringProperty<UserDataModel>(_entities[0].properties[2]);

  /// see [UserDataModel.participants]
  static final participants =
      QueryIntegerProperty<UserDataModel>(_entities[0].properties[3]);

  /// see [UserDataModel.price]
  static final price =
      QueryDoubleProperty<UserDataModel>(_entities[0].properties[4]);

  /// see [UserDataModel.link]
  static final link =
      QueryStringProperty<UserDataModel>(_entities[0].properties[5]);

  /// see [UserDataModel.key]
  static final key =
      QueryStringProperty<UserDataModel>(_entities[0].properties[6]);

  /// see [UserDataModel.accessibility]
  static final accessibility =
      QueryDoubleProperty<UserDataModel>(_entities[0].properties[7]);
}
